### PR TITLE
Telegram Chat Bot - BOTSY BOT

### PR DESCRIPTION
**Pull request by kanishkaa24**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you receive communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
Suggestions: 
1. Add video link in the readme.md
2. remove unnecessary files from the PR

**Comment by kanishkaa24** [comment]
There are no unnecessary files. I will add the video link ASAP.

**Review by theAdityaNVS — CHANGES_REQUESTED** [review]
Add screenshots and a demo video in readme.

**Comment by kanishkaa24** [comment]
> Add screenshots and a demo video in readme.

Definitely

**Comment by jainaayush01** [comment]
image
please add it correctly..

Update: There was an issue with the GitHub

**Comment by kanishkaa24** [comment]
> image
> please add it correctly.

The repository contains the relative links. It will be visible as soon as it is merged. For exact reference, please checkout https://github.com/kanishkaa24/Telegram-bots/tree/main/TelegramBot. It is the forked version. I have not updated the video yet. I will do it as soon as possible.

**Comment by jainaayush01** [comment]
Do add what are the commands and what are the features in the readme.md

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
I don't see this bot aligning with the IBD theme.

Can you come up with something innovative and unique which aligns with the theme and boosts your productivity?

**Comment by kanishkaa24** [comment]
This is my final submission. Thank you for your patience. I have added images and the video.

**Review by archithdwij — CHANGES_REQUESTED** [review]
@kanishkaa24 If you could change you bot's behavior in such a way that, it responds to generic work related queries, that would make it productive. It could be modified based on the organization's requirement. 
Requesting you to try making these changes so that we can move forward 😃

**Comment by kanishkaa24** [comment]
> @kanishkaa24 If you could change you bot's behavior in such a way that, it responds to generic work related queries, that would make it productive. It could be modified based on the organization's requirement.
> Requesting you to try making these changes so that we can move forward 😃

Can you give some examples?
What kind of queries are you looking forward for this bot to address?

**Comment by archithdwij** [comment]
@kanishkaa24 It could be something like, what are the meeting I have today, what are the tasks in my todo, do I have any mails/messages, something like this. Few of these might be a little advanced but it will definitely add value and make your project stand out! The more data you feed, the more details and accuracy you will receive in return ⭐

**Comment by kanishkaa24** [comment]
> @kanishkaa24 It could be something like, what are the meeting I have today, what are the tasks in my todo, do I have any mails/messages, something like this. Few of these might be a little advanced but it will definitely add value and make your project stand out! The more data you feed, the more details and accuracy you will receive in return ⭐

I have transformed this bot into a FAQ chat bot. This bot can now answer queries related to CRIO #IBD Remote Working Tools Edition via a Menu.

**Comment by kanishkaa24** [comment]
I have also added more images and a live video of the concept.

**Comment by jainaayush01** [comment]
Suggested changes:
Can you generalize the bot for other events also, like user can give the FAQs and then any other who wants to find the info relevant to the event, then they can start by typing event __eventName__.

you have a limited time of 4-5 hours till evening if you can come up with this, we can look forward to merging this PR

**Review by archithdwij — APPROVED** [review]
@kanishkaa24 I can see that you have worked on generalizing the bot to a certain extent. Answering IBD related questions is a good idea. We are going to merge your PR but recommend you to provide steps to make the bot generalized for any such events to make it more productive. Congratulations!

**Comment by archithdwij** [comment]
@all-contributors Please add @kanishkaa24 for code, design, infra, idea

**Pull request merged**
