### PR TITLE
PDF_GENERATION_AND_TEXT_SUMMARIZATION

### PR DESCRIPTION
**Pull request by Jaykishan84**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [X ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [X ] Added readme.md to my project folder with relevant information.
- [X ]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [X ] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [X ] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
Please add the demo video and publish the bot to telegram so that we can check the functionality

**Comment by Jaykishan84** [comment]
The suggested changes have been made. Let me know if anything else is required.

**Review by jainaayush01 — APPROVED** [review]

**Review by archithdwij — APPROVED** [review]
Solid work @Jaykishan84 👏 Congratulations on getting your PR merged 😃

**Comment by archithdwij** [comment]
@all-contributors Please add @Jaykishan84 for code, design, idea, infra

**Pull request merged**
